name: Activate Unity License

on:
  workflow_dispatch:

jobs:
  activate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Request manual activation file
        uses: game-ci/unity-request-activation-file@v2
        id: request
        env:
          UNITY_VERSION: 6000.3.16f1

      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ${{ steps.request.outputs.filePath }}
